// Generated by ts-to-zod
import { z } from "zod";

const locationSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
});

const imageSchema = z.object({
  sequence: z.number(),
  url: z.string(),
});

export const contentSchema = z.object({
  recommendationReason: z.string(),
  activity: z.string(),
});

export const placeBaseSchema = z.object({
  id: z.string(),
  googlePlaceId: z.string(),
  placeName: z.string(),
  primaryType: z.string(),
  formattedAddress: z.string(),
  location: locationSchema,
  content: contentSchema,
  images: z.array(imageSchema),
  openingHours: z.array(z.string()),
  openNow: z.string(),
  categoryGroup: z.string(),
  category: z.string(),
});

export const placeSchema = placeBaseSchema.extend({
  distance: z.number(),
});

export const placeDetailDataSchema = z.object({
  status: z.string(),
  message: z.string(),
  data: z.object({
    place: placeBaseSchema,
    directionSummary: z.object({
      distance: z.string(),
      duration: z.string(),
    }),
  }),
});

export const placeDataSchema = z.object({
  status: z.string(),
  message: z.string(),
  data: z.object({
    content: z.array(placeSchema),
    page: z.number(),
    size: z.number(),
    numberOfElements: z.number(),
    hasNext: z.boolean(),
  }),
});
